### ISSUE TITLE
DHT 22 header rotation needed

### ISSUE THREAD

**Issue by pjb304** [ch2i/iC880A-Raspberry-PI#4]
The DHT header needs to be rotated 180 degrees so that when soldered on it does not clash with the ic880a PCB.  At the moment it has to be soldered on at an angle.

![image](https://cloud.githubusercontent.com/assets/1146400/26350299/96ba79bc-3faa-11e7-8218-c61d3e0b97b1.png)

**Comment by hallard** [comment]
Hi,
Thanks for pointing up 
It's now corrected on V1.2 with also some new features
