### ISSUE TITLE
GPS connection for iC880A

### ISSUE THREAD

**Issue by Octoate** [ch2i/iC880A-Raspberry-PI#6]
Hi,
thanks for your great work with the backplane. It is very versatile and great to use!
However, I am missing one feature: The support for a GPS module with PPS signal. It would be great if you can add a header for a GPS module (e.g. for a GN-801 GPS module) that connects the UART to the Raspberry Pi and the PPS pin of the module to pin 19 of the IMST iC880A. Currently I am modifying the board by myself, but it would be great if I can just add a header and connect the GPS module there.
I know there has been a discussion about the sense of this addon, but the GPS module is very cheap so why not adding it :-)?

Best regards,
Tim

**Comment by hallard** [comment]
HI @Octoate 
Yes, sure it could be easy, would you mind give me reference or pointer on the header you need? The GPS board you want to put on
Thanks

**Comment by Octoate** [comment]
Well, I guess it would make sense to use a GPS sensor that is widely available, so I wouldn't recommend the one, I am using here (and it doesn't have a pin header anyway ;-)). Maybe the pin header for the NEO6MV2 would be nice like on this boards:

https://www.ebay.com/itm/GY-NEO6MV2-NEO-6M-GPS-Module-Board-with-Antenna-for-Arduino-Raspberry-Pi/142660988559?hash=item213741ee8f:g:vuIAAOSw61haaANE

or, because it has a good availability, the one of the Adafruit Ultimate GPS:

https://www.adafruit.com/product/746

What do you think?

**Comment by hallard** [comment]
I'm using this [one](https://www.electrodragon.com/product/gnss-module-atgm336h/) on my [RAK831 PI Zero Board](https://github.com/hallard/RAK831-Zero) Would it be okay for you ?

Another Idea would be using an USB One, unfortunately both same pinout execpt TX/RX reversed, that's a same, so USB Only
https://www.electrodragon.com/product/neo-6m-gps-module-r2/

But It's easy to wire this kind on board on existing shield, RX/RX/GND are available on FTDI connector, just need to get 3V3 and set PPS to a GPIO available (GPIO13 for example on Groove connector). Of course change GPIO to reflect this change if you want to use GPS with packet forwarder.
